name: Generate Animated SVG

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *" # 每分钟触发一次（仅作为演示）

jobs:
  generate-animation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Generate Animated SVG Frames
        run: |
          mkdir -p svg_frames
          for i in {1..300}; do
            r=$((RANDOM % 256))
            g=$((RANDOM % 256))
            b=$((RANDOM % 256))
            echo "<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200' viewBox='0 0 200 200'>
                    <rect x='20' y='20' width='160' height='160' rx='20' ry='20' fill='rgb($r, $g, $b)' />
                  </svg>" > svg_frames/frame_$i.svg
            sleep 0.016 # 模拟每秒 60 帧
          done

      - name: Commit and Push Updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mv svg_frames/frame_$(shuf -i 1-300 -n 1).svg animated.svg
          git add animated.svg
          git commit -m "Update Animated SVG Frame"
          git push
